Transfers : Modify the verify_checksum parameter passed to FTS. Closes #1048
rucio/rucio pull request #1049
Opened 2018-04-13 14:23 UTC by cserf

Transfers : Modify the verify_checksum parameter passed to FTS. Closes #1048

2018-04-16 06:32 UTC, mlassnig reviewed
looks good to me. @bari12 ?

2018-04-16 11:24 UTC, bari12 requested changes

2018-04-16 11:24 UTC, bari12 commented on lib/rucio/core/transfer.py
> +                if rse_attrs[dest_rse_id].get('verify_checksum', 'True') == 'False':
I think we should put .upper() or .lower() into these, just to make it save.

2018-04-17 13:34 UTC, bari12 commented
Ok travis is a bit weird one these ones. I tested this manually and it works. Will force merge.

2018-04-17 13:34 UTC, merged