rsemgr: deletion of left-overs after 1st upload attempt Fix #1359
rucio/rucio pull request #1364
Opened 2018-07-19 13:18 UTC by TomasJavurek

rsemgr: deletion of left-overs after 1st upload attempt Fix #1359

2018-07-20 13:36 UTC, cserf submitted a review, later dismissed

2018-07-20 13:39 UTC, TWAtGH requested changes

2018-07-20 13:39 UTC, TWAtGH commented on lib/rucio/rse/rsemanager.py
> +                        continue
I think gs should be set to False before the continue

2018-07-25 12:59 UTC, TWAtGH approved these changes

2018-07-25 17:18 UTC, merged