Core: add ability to limit the total size usage of an RSE Resolves #1965
rucio/rucio pull request #1966
Opened 2019-01-11 17:06 UTC by illingwo

Core: add ability to limit the total size usage of an RSE Resolves #1965

2019-01-14 12:06 UTC, bari12 requested changes
I think it's good like this. I only found 1 missing space. For the question if it should be an RSE-limit or RSE-Attribute. For now I think RSE-limit is the correct one to do, although it makes me wonder if we really need this separate table. For the sake of simplicity, it might be better to just make these RSE-attributes as well and get rid of the rse_limits table. But this is stuff for future thought.
Please add a test-case where the `RSEOverQuota` exception is raised.

2019-01-14 12:06 UTC, bari12 commented on lib/rucio/core/rse_selector.py
> +        :existing_rse_size:                 Dictionary of size of files already present at each rse
Space missing

2019-01-16 18:55 UTC, illingwo commented on lib/rucio/core/rse_selector.py
> +        :existing_rse_size:                 Dictionary of size of files already present at each rse
I've fixed the comment spacing, added a test case, and fixed a bug in the NONE grouping repair function that I'd overlooked before.

I've been wondering what the motivation for the separate RSE limit table is - they're less discoverable than attributes (and there's no CLI commands). But given they do exist it was the obvious place to put this.

2019-01-17 09:21 UTC, bari12 commented on lib/rucio/core/rse_selector.py
> +        :existing_rse_size:                 Dictionary of size of files already present at each rse
To me the separation doesn't make much sense and I can't quite remember our reasoning when we designed it that way. But for now it's the right place to put that information, we can do some consolidation (and get rid of the table) later.

2019-01-17 09:27 UTC, vingar commented on lib/rucio/core/rse_selector.py
> +        :existing_rse_size:                 Dictionary of size of files already present at each rse
RSE attributes are mostly tags/string attributes and limits numerical values with some constraints. I guess It looked cleaner to separate them. With a better support of various types and theirs respective constraints in the rse attributes table, it makes sense to converge on using only this table.

2019-01-18 14:12 UTC, bari12 approved these changes

2019-01-18 14:12 UTC, merged