patch: added get se config and set se config in fts3 #2227
rucio/rucio pull request #2278
Opened 2019-03-05 15:22 UTC by DilaksunB

patch: added get se config and set se config in fts3 #2227

2019-03-06 12:05 UTC, bari12 commented
I am not quite sure why github thinks that the entire file changed. It shows 1500+ lines as changed. Please check if your editor is adding some kind of new line-ending character to each line.

2019-03-06 12:50 UTC, DilaksunB commented
I messed up with the line endings, should be fixed now.

2019-03-06 15:14 UTC, bari12 requested changes

2019-03-06 15:14 UTC, bari12 commented on lib/rucio/transfertool/fts3.py
> +        returns a Json result for the configuration of a storage element.
:returns: ...

2019-03-06 15:14 UTC, bari12 commented on lib/rucio/transfertool/fts3.py
> +        returns: JSON post response in case of success, otherwise raise Exception.
:returns:

2019-03-07 10:38 UTC, bari12 approved these changes

2019-03-07 10:38 UTC, merged