Clients: Fix installation issues with Py2->Py3 and hash sum #2480
rucio/rucio pull request #2481
Opened 2019-04-15 08:40 UTC by XeBoris

There are two issues observed in: 
  - Installation in Python 3.6.8 failed because of bad translated Py2->Py3 code in rucio/lib/rucio/rse/protocols/storm.py when it comes to evaluate the exceptions.
  - The hash sum calculation failed due to an encoding error when the hash sum is calculated for the final path definition. (protocols.py)

Both are addressed in this pull request.

2019-04-17 14:18 UTC, bari12 requested changes

2019-04-17 14:18 UTC, bari12 commented on lib/rucio/client/uploadclient.py
> +    def __init__(self, _client: object = None, logger: object = None, tracing: object = True) -> object:
The type hints are not backwards compatible unfortunately 😞

2019-04-17 14:18 UTC, bari12 commented on lib/rucio/client/uploadclient.py
> +                logger.info("Here")
Please remove

2019-04-17 14:18 UTC, bari12 commented on lib/rucio/common/pcache.py
> +            for fd in range(0, maxfd + 1):
Why not just use range in both cases?

2019-04-23 07:26 UTC, XeBoris commented on lib/rucio/common/pcache.py
> +            for fd in range(0, maxfd + 1):
Indeed, this is much simpler.

2019-04-23 07:27 UTC, XeBoris commented on lib/rucio/client/uploadclient.py
> +                logger.info("Here")
oh! I forgot to delete it before uploading.

2019-04-23 07:27 UTC, XeBoris commented on lib/rucio/client/uploadclient.py
> +    def __init__(self, _client: object = None, logger: object = None, tracing: object = True) -> object:
Right! I changed it back

2019-04-24 12:20 UTC, XeBoris commented
I submitted the requested changes but the build still fails. The log files saying it is failing only for one test (py2.7 with Oracle) and Travis ends with these lines in the log file (everything before looks reasonable to me):
```
RSE (CLIENTS): get protocols for operations of rse. ... ok
RSE (CLIENTS): get protocols for operations of rse (RSEOperationNotSupported). ... 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Furthermore, Python3.6 tests seems to fail since flake8 is missing:
```
===============================
Running flake8                 
===============================
./tools/travis/check_syntax.sh: line 23: flake8: command not found
```

2019-04-24 12:54 UTC, bari12 commented
Hi Boris,
Yes, the oracle test hangs sometimes, I am usually just restarting them, but now on vacation so I didn't see this right away.
The missing flake8 for py36 we know about. This will be fixed as well.
Thanks!

2019-05-16 13:58 UTC, merged