Documentation: Change url_prefix to match actual endpoint Fix #3630
rucio/rucio pull request #3631
Opened 2020-05-23 07:37 UTC by didithilmy

Documentation: Change url_prefix to match actual endpoint Fix #3630

2020-05-26 12:45 UTC, bari12 requested changes
Also tests are failing; But that could be related to #3640

2020-05-26 12:45 UTC, bari12 commented on AUTHORS.rst
> +- Muhammad Aditya Hilmy <didithilmy@gmail.com>
Add year

2020-05-26 12:50 UTC, bziemons commented
> Also tests are failing; But that could be related to #3640

Looking at the error of the syntax test, it is unrelated to #3640

2020-05-26 13:09 UTC, didithilmy commented
> Also tests are failing; But that could be related to #3640

I'm not sure why it happened. If I see the Travis logs, the files that are causing the error weren't even included in my changes. As I recall, when I checked out the repo from `master` it was already failed. Any suggestion on how to fix this?

2020-05-26 13:49 UTC, bziemons commented
The offending line seems to be this one: https://github.com/didithilmy/rucio/blob/9cd521385549a312442cb8d88106ed0f6852fd1d/lib/rucio/web/rest/flaskapi/v1/exporter.py#L72

2020-05-26 14:02 UTC, bziemons commented
> Any suggestion on how to fix this?

Can you try to change the `bp.add_url_rule('', …` to `bp.add_url_rule('/', …` in exporter.py and importer.py in lib/rucio/web/rest/flaskapi/v1 and see if that fixes the issue?

2020-05-26 14:12 UTC, didithilmy commented
> The offending line seems to be this one: https://github.com/didithilmy/rucio/blob/9cd521385549a312442cb8d88106ed0f6852fd1d/lib/rucio/web/rest/flaskapi/v1/exporter.py#L72
> 
> which is the same in `master` and `next`, but this error is probably coming up now because of this change: https://github.com/rucio/rucio/pull/3631/files#diff-72e4556e2f5d8168cb86e424174fe576

Okay that makes sense. I've pushed the changes as suggested by @bziemons

2020-05-29 13:28 UTC, bari12 approved these changes

2020-05-29 13:28 UTC, merged