Rules: Add a parameter to ignore rule locks and use it when denying rules #3843
rucio/rucio pull request #3892
Opened 2020-07-29 15:55 UTC by ericvaandering

Fixes the issue where CMS is not able to use the Web UI to deny rules on tape sites.

Please apply to 1.23 branch and master

2020-08-04 09:27 UTC, bari12 requested changes

2020-08-04 09:27 UTC, bari12 commented on lib/rucio/core/rule.py
> +            rule = (session.query(models.ReplicationRule)
It's only cosmetics, but can you please remove the enclosing parenthesis? Just for symmetry with the rest of the code. (The line-breaks are fine)

2020-08-04 14:46 UTC, ericvaandering commented
I will. But this is now the preferred way. :-)

2020-08-05 13:28 UTC, bari12 approved these changes

2020-08-05 13:28 UTC, merged