Reaper : Make the pause_deletion expiration time configurable : Close…
rucio/rucio pull request #4140
Opened 2020-11-23 09:32 UTC by cserf

Reaper : Make the pause_deletion expiration time configurable : Close #4138

2021-01-14 09:20 UTC, mlassnig commented on lib/rucio/daemons/reaper/reaper2.py
> +        semaphore = REGION.get('semaphore')
i don't think this is correct. multiple reapers on the same node could set/delete this value. the REGION.get() needs to atomically wait, not check it with an `if` later. or am i misunderstanding what you're trying to accomplish here?

2021-03-16 14:37 UTC, bari12 requested changes
Hi @cserf 
Sorry for the long delay on this. A few comments.

2021-03-16 14:37 UTC, bari12 commented on lib/rucio/daemons/reaper/reaper2.py
> +        if semaphore is NO_VALUE:
The semaphore should be removed. I don't think it has the wished effect and will not do much.

2021-03-16 14:37 UTC, bari12 commented on lib/rucio/daemons/reaper/reaper2.py
> +        memcached_expiration_time = get('reaper', 'memcached_expiration_time')
Let's call this `pause_deletion_time` or so. It has nothing todo with memcache per se, that's just the mechanism how it is implemented.

2021-03-16 14:37 UTC, bari12 commented on lib/rucio/daemons/reaper/reaper2.py
> +                payload_cnt = REGION.get('payload_cnt', expiration_time=30)
I would build this into the `list_payload_counts` directly.

2021-04-13 09:33 UTC, bari12 commented
Closing, most of this is solved by the PR @tbeerman did already. If needed we can add a few missing parts still.

2021-04-13 09:33 UTC, closed without merging