Monitoring & Logging: add formatted_logger to protocols #4220
rucio/rucio pull request #4301
Opened 2021-02-04 17:12 UTC by tbeerman

2021-02-05 08:24 UTC, tbeerman commented
I "just" wanted to add the prefixed logger to the gfal protocol but I had to change a some more places from the clients to automatix and the reaper since it's all connected somehow.

2021-02-05 12:03 UTC, bziemons submitted a review, later dismissed
Changes a few log outputs. As long as any third-party program that may or may not read them is fine with it, this looks good

2021-02-05 12:03 UTC, bziemons commented on lib/rucio/rse/rsemanager.py
>  _logger = logging.getLogger(__name__)
remove unused code

2021-02-11 13:55 UTC, bziemons requested changes
The usage of the name `logger` as a parameter, class attribute and global module variable makes it extremely hard to see through this. I know this is old code, but it would be extremely helpful if you could clean this up.

2021-02-11 13:55 UTC, bziemons commented on lib/rucio/client/downloadclient.py
> +            logger(logging.DEBUG, 'Tracing is turned off.')
above:
```diff
 if not logger:
             logger = logging.getLogger('%s.null' % __name__)
             logger.disabled = True
+            logger = logger.log
```

2021-02-11 13:55 UTC, bziemons commented on lib/rucio/client/uploadclient.py
> +    def __init__(self, _client=None, logger=logging.log, tracing=True):
Check consistency see above. If you add `logger=logging.log` here, check that no-one explicitly passes `None` and remove the `if not logger:` below.

2021-02-11 13:55 UTC, bziemons commented on lib/rucio/client/uploadclient.py
> +    def _create_protocol(self, rse_settings, operation, force_scheme=None, logger=logging.log):
be consistent in this function as well. I would suggest using `self.logger` if it is available, instead of a logger parameter.

2021-02-11 13:55 UTC, bziemons commented on bin/rucio
>      logger = None
this module-wide variable is shadowed by the parameter "logger" and makes it hard to track usage of either in the review. I would suggest renaming this to something like `module_logger`

2021-02-12 10:59 UTC, bziemons requested changes

2021-02-12 10:59 UTC, bziemons commented on lib/rucio/client/uploadclient.py
>          :param logger:      - logging.Logger object to use for uploads. If None nothing will be logged.
just saw this doc string here, should be updated wherever present and probably added when absent

2021-02-12 10:59 UTC, bziemons commented on lib/rucio/daemons/automatix/automatix.py
> +                status = upload(files=lfns, scope=scope, metadata=metadata, rse=site, account=account, source_dir=tmpdir, dataset_lifetime=dataset_lifetime, did=dsn, set_metadata=set_metadata)
fehlt hier ein `logger=logger` ?

2021-02-12 18:03 UTC, bziemons approved these changes

2021-02-15 09:51 UTC, merged