Documentation: Fix small typos and grammatical mistakes #4321
rucio/rucio pull request #4322
Opened 2021-02-11 17:17 UTC by OCM-7898

Fixed typos and grammatical mistakes in  bin/rucio-conveyor-fts-throttler,bin/rucio-conveyor-throttler,bin/rucio-hermes2,bin/rucio-necromancer

2021-02-11 18:47 UTC, bziemons requested changes

2021-02-11 18:47 UTC, bziemons commented on bin/rucio-conveyor-fts-throttler
> +of tranfser failures due to time outs, it is usually due to bad connectivity and the amount of failures can be
almost…!

2021-02-11 19:29 UTC, OCM-7898 commented on bin/rucio-conveyor-fts-throttler
> +of tranfser failures due to time outs, it is usually due to bad connectivity and the amount of failures can be
Hopefully it's fixed now

2021-02-11 20:51 UTC, bziemons approved these changes
Thank you very much! :)

2021-02-15 10:06 UTC, bari12 commented
👍

2021-02-15 10:06 UTC, merged