Subscriptions columns for filter and replication_rules need to be extended : Closes #4298
rucio/rucio pull request #4425
Opened 2021-03-15 17:29 UTC by cserf

Subscriptions columns for filter and replication_rules need to be extended : Closes #4298

2021-03-19 15:16 UTC, bari12 requested changes
Needs also to be reflected in the `subscriptions_history`.
For the `schema.sql` this is missing completely, but there needs also to be a migrate script for this. For the `models.py` it is fine, since it is derived.

2021-04-09 13:55 UTC, bari12 requested changes

2021-04-09 13:55 UTC, bari12 commented on lib/rucio/db/sqla/migrate_repo/versions/e138c364ebd0_extending_columns_for_filter_and_.py
> +        alter_column('subscriptions', 'filter', existing_type=sa.String(2048), type_=sa.String(4000), schema=schema)
You need to alter subsriptions_history too in upgrade/downgrade.

2021-04-13 15:23 UTC, cserf commented
Added  subscriptions_history upgrade and downgrade + squash commits

2021-04-14 12:32 UTC, bari12 approved these changes

2021-04-14 12:32 UTC, merged