WebUI: Removed Jira Issue Reference & Redirected to GitHub Issues Fix #4426
rucio/rucio pull request #4427
Opened 2021-03-16 07:25 UTC by DhruvSondhi

Fixes Jira Reference in reporting an error message 
------------------
This PR aims to fix the reference to the Jira archived project in the error message

2021-03-22 06:35 UTC, dchristidis reviewed
Thanks for the patch. However, my personal preference is to remove this entirely. My main motivation is that there’s little gain suggesting users to submit issues exclusively for this part of the UI. Additionally, the Rucio Web UI has been used in production for a long time.

Maybe other reviewers have a different opinion.

2021-03-22 07:59 UTC, mlassnig commented
I think it's fine to keep it. Sometimes users need a little convincing to report things, and extra messages might convince them to do that.

The ID should be renamed though :-) That's still called `jira_alert` there.

2021-03-25 14:39 UTC, bziemons requested changes
For the time being, please also change the file `lib/rucio/web/ui/templates/request_rule.html`

2021-03-25 14:48 UTC, bziemons approved these changes

2021-03-25 16:16 UTC, merged