Testing: Upgrade of flake8 version; #4162
rucio/rucio pull request #4588
Opened 2021-04-28 14:19 UTC by bari12

This will still break until #4564 is merged, since I did not fix the flake8 errors there. Will rebase once merged.

2021-04-28 15:24 UTC, bziemons commented
Hi Martin, could you also upgrade pylint? I need this for compatibility with Python 3.9 and 2.8.2 is compatible with 3.6 and works well: 
[Change on Py3.8/3.9 branch](https://github.com/bziemons/rucio/commit/06ef24c494c5027a0182c37ed190e9ad83432ec8#diff-f738270eb643c461e5b33c8a8778325c400c5071554bf0aac10d017600eb2087R9)
[Test run with that change](https://github.com/bziemons/rucio/actions/runs/792427880)

2021-04-28 16:01 UTC, bari12 commented
Yes, I am already preparing a second PR for this... 😄 
Just wanted to first check if there are any major changes I have to make due to newer pylint.

2021-04-30 10:05 UTC, bziemons commented on lib/rucio/api/subscription.py
> +
old copyright needs to be removed

2021-04-30 10:08 UTC, bziemons commented on lib/rucio/web/ui/flask/common/utils.py
> +                               + "In case you provided your account name, make sure it is known to Rucio.")   # NOQA: W503
maybe make a proper multiline string out of this:
```py
msg=("ab"
     "cd")
```

2021-05-21 09:13 UTC, bziemons requested changes

2021-05-21 09:13 UTC, bziemons commented on lib/rucio/api/subscription.py
> +
:ping_pong: 

Hint: it is below this header

2021-05-21 09:25 UTC, bziemons approved these changes

2021-05-21 11:28 UTC, merged