Core & Internals: rework tombstone handling. Closes #4491, #4436 and #4188
rucio/rucio pull request #4594
Opened 2021-04-30 07:37 UTC by rcarpa

Always set a default tombstone on any replica creation. Introduce two
rse attributes which allow to customize the behavior per rse:

One allows to define the normal replica creation tombstone
The other used to configure the multihop temporary replica tombstone
As a tombstone will now be added when the intermediate multihop replica
is created, remove the redundant protection which was touching the
tombstone in the finisher.
Add a submitter test which ensures that multihop sources are created;
and that the multihop request are created with a tombstone.

2021-04-30 07:37 UTC, rcarpa commented
The first commit was submitted as a separate PR (#4577)

2021-05-12 08:07 UTC, mlassnig reviewed
looks good from a code point of view. @bari12 can you check for semantics as well pls.

2021-05-19 07:24 UTC, bziemons submitted a review, later dismissed
lgtm

2021-05-19 09:11 UTC, bari12 requested changes
I think there is a misconception here 😄 

The default_tombstone should only be applied for RSEs which have the `tombstone_delay` set. For all the other RSEs, current behaviour should be kept. As far as as I can see here, we would put the 2 week tombstone on everything which does not have a `tombstone_delay` set.

For the intermediate replicas of multihops I think we need to do it a bit different. There we should have a global (config table) variable which specifies the tombstone delay.

2021-05-19 15:42 UTC, rcarpa commented
I updated thing to not set any default tombstone on normal replica creation. And to set it two hours into the future for the multihop tombstone. I'll work on a separate commit now to make the multihop_tombstone_delay also available as a config variable, which will be used for RSEs which don't have it set per-rse.

2021-06-15 15:11 UTC, bari12 approved these changes
Note: for the more strict replica deletion selection (which filters out sources) we have to see if this affects deletion too negatively. Perhaps we have to switch here to only exclude sources we are actually using.

2021-06-15 15:12 UTC, bari12 commented
Merging as a feature (For 1.26)

2021-06-15 15:12 UTC, merged