Rules: Allow repair when ignore_availability=True
rucio/rucio pull request #4713
Opened 2021-07-01 17:20 UTC by nsmith-

Fixes #4152

2021-07-01 17:24 UTC, nsmith- commented on lib/rucio/tests/test_judge_repairer.py
> -        assert(RuleState.STUCK == get_rule(rule_id)['state'])
This behavior is altered, so the old test case would fail. Based on our issue discussion, it sounds like this is OK.

2021-07-27 22:00 UTC, nsmith- commented
I think the test failure is intermittent?

2021-08-05 08:43 UTC, bari12 requested changes
Sorry for the long delay @nsmith- 
PR is good, only one note
`lib/rucio/tests/test_judge_repairer.py:318:9: E306 expected 1 blank line before a nested definition, found 0`
Also please rebase

2021-08-06 16:04 UTC, nsmith- commented
Looks like everything except integration tests passed. Is this expected?

2021-08-07 10:55 UTC, bari12 commented
Yes, they are unfortunately a bit flaky at the moment.

2021-08-11 14:22 UTC, bari12 approved these changes

2021-08-11 14:25 UTC, merged

2021-10-04 20:19 UTC, nsmith- commented
Why did this not make it into 1.26.4?

2021-10-06 15:15 UTC, bari12 commented
It's part of 1.26.2, so should be in 1.26.4 too?

2021-10-06 18:57 UTC, nsmith- commented
Sorry you're right, I was going off github hints and didn't realize you cherry-pick all the patches off master