Core & Internals: Enforce naming restrictions on algorithms registered from policy packages #4830
rucio/rucio pull request #4842
Opened 2021-09-13 14:50 UTC by jamesp-epcc

This PR ensures that algorithms registered by policy packages in multi-VO Rucio installations include the VO name at the start of the algorithm name, to avoid name clashes.

2021-10-04 15:45 UTC, mlassnig requested changes

2021-10-04 15:45 UTC, mlassnig commented on lib/rucio/common/exception.py
> +        self.message = 'The given algorithm name is not valid for this VO'
add actual algorithmname to message. can the validation string also be added?

2021-10-12 08:36 UTC, jamesp-epcc commented on lib/rucio/common/exception.py
> +        self.message = 'The given algorithm name is not valid for this VO'
I've added both to the exception message.

2021-10-27 11:14 UTC, mlassnig commented
There's a merge conflict that needs to be resolved.

2021-11-03 11:41 UTC, jamesp-epcc commented
> There's a merge conflict that needs to be resolved.

I've rebased with latest master.

2021-11-24 08:42 UTC, bari12 approved these changes

2021-11-24 08:42 UTC, merged