Core & Internals: merged changes #4807
rucio/rucio pull request #4844
Opened 2021-09-13 17:18 UTC by ivmfnal

merged all changes

2021-10-04 15:46 UTC, mlassnig commented on lib/rucio/web/rest/flaskapi/v1/locks.py
> +        if did_type not in ('dataset', 'container'):
don't we have a collection type that can be checked here? or is the string check required?

2021-10-06 17:41 UTC, ivmfnal commented on lib/rucio/web/rest/flaskapi/v1/locks.py
> +        if did_type not in ('dataset', 'container'):
What are you suggesting ?

2021-10-08 13:40 UTC, bari12 reviewed
Hi @ivmfnal 
I think this is good. I have only one comment (see below) which is more a conceptual, then implementation question and would mirror a bit the behaviour in other clients. Please have a look.

2021-10-08 13:40 UTC, bari12 commented on lib/rucio/client/lockclient.py
> +    def get_locks_for_datasets(self, dataset_list):
Just food for thought:

I wonder if we should just name this `get_datasetlocks_for_dids`. The reason is, in general Rucio should be able to handle inputs as dids, no matter if they are files/datasets/containers (Files does not make sense in this case)
This case we could merge the `get_locks_for_datsets` and `get_container_locks` case. (I mean, you might even want to get dataset locks for multiple containers)

2021-10-08 14:23 UTC, ivmfnal commented on lib/rucio/client/lockclient.py
> +    def get_locks_for_datasets(self, dataset_list):
Let me see if I understand this... Are you suggesting to have a method which will take a list of container or dataset DIDs and get all the locks for all the files found in the listed containers and datasets ?

2021-10-25 13:41 UTC, bari12 submitted a review, later dismissed
Hi @ivmfnal 
In principle this is correct, but the layering is wrong which might lead to some performance issues due to the number of transactions being opened. (DB Operators are already not happy about this) I added some suggestions to move this basically to the core. I think it should mostly be moving code around, the underlying code is correct.
Thanks

2021-10-25 13:41 UTC, bari12 commented on lib/rucio/client/lockclient.py
> +    def get_locks_for_dids(self, dids):
`get_dataset_locks_for_dids` instead?

2021-10-25 13:41 UTC, bari12 commented on lib/rucio/client/lockclient.py
> +        Get list of locks for for all the files fund, recursively, in the listed datasets or containers.
fund -> found?

2021-10-25 13:41 UTC, bari12 commented on lib/rucio/web/rest/flaskapi/v1/locks.py
> +from rucio.core.did import list_child_datasets, get_did
The REST layer should not directly interact with the core. We need to layer this
REST -> API -> CORE

2021-10-25 13:41 UTC, bari12 commented on lib/rucio/web/rest/flaskapi/v1/locks.py
> +                    for dataset_info in list_child_datasets(internal_scope, name):
Ok I thought a little bit about this especially in regards to the recent discussion with DB operators.

We need to put this functionality to the core (See comment above). The problem, even if we just put this to the API and call the core like this from there is that we would create a new session for each call in these loops. This creates a lot of transactions on the DB. You need to move this functionality to the core where only one session is used.

Code should not change a lot, it just needs to be relocated.

2021-10-25 13:41 UTC, bari12 commented on lib/rucio/web/rest/flaskapi/v1/locks.py
> +                        for dataset_info in list_child_datasets(internal_scope, name):
Same here, see comment above.

2021-11-22 13:52 UTC, bari12 requested changes
GTG, one small change, but otherwise this can be included.

2021-11-22 13:52 UTC, bari12 commented on lib/rucio/core/lock.py
> +    from rucio.core.did import list_child_datasets
At the top `rucio.core.did` is already imported. I think you can just address this as `rucio.core.did.list_child_datasets`

2021-11-22 13:52 UTC, bari12 commented on lib/rucio/core/lock.py
> +                did_info = rucio.core.did.get_did(scope, name)
You have to hand through the session here, otherwise it leaks.

2021-11-22 15:29 UTC, closed without merging