VP integration - create a DB table for the placements
rucio/rucio pull request #4934
Opened 2021-10-22 18:37 UTC by ivukotic

This addresses issue #4933.

2021-10-29 13:21 UTC, bari12 requested changes
Also remove the `GeoLite2-City.mmdb` file please

2021-10-29 13:21 UTC, bari12 commented on .vscode/settings.json
> +{
Remove this file

2021-10-29 13:21 UTC, bari12 commented on lib/rucio/core/did_meta_plugins/did_column_meta.py
> +    def set_metadata(self, scope, name, key, value, recursive=False, session=None):  # ILIJA
Remove comment

2021-10-29 13:21 UTC, bari12 commented on lib/rucio/core/did_meta_plugins/json_meta.py
> +class JSONDidMeta(DidMetaPlugin):  # ILIJA
Remove comment

2021-10-29 13:21 UTC, bari12 commented on testDIST.py
> +from math import asin, atan2, cos, radians, sin, sqrt
Remove file

2021-10-29 13:21 UTC, bari12 commented on testGEOIP.py
> +import socket
Rmove File

2021-10-29 13:21 UTC, bari12 commented on testHUGE.py
> +import xmltodict
Remove File

2021-10-29 13:21 UTC, bari12 commented on testSORTING.py
> +# UC
Remove File

2021-10-29 13:21 UTC, bari12 commented on lib/rucio/db/sqla/migrate_repo/versions/9a45bc4ea66d_add_vp_table.py
> +                     sa.Column('scope', sa.String(25)),
sa.String(get_schema_value('SCOPE_LENGTH')))

2021-10-29 13:21 UTC, bari12 commented on lib/rucio/db/sqla/migrate_repo/versions/9a45bc4ea66d_add_vp_table.py
> +                     sa.Column('name', sa.String(255)),
sa.String(get_schema_value('NAME_LENGTH')))

2021-10-29 13:21 UTC, bari12 commented on lib/rucio/db/sqla/migrate_repo/versions/9a45bc4ea66d_add_vp_table.py
> +        create_table('did_virtual_placements',
Let's just call it `virtual_placements` scratch the did.

2021-10-29 13:21 UTC, bari12 commented on lib/rucio/db/sqla/migrate_repo/versions/9a45bc4ea66d_add_vp_table.py
> +        create_primary_key('DID_VP_PK', 'did_virtual_placements', ['scope', 'name'])
--> VP_PK

2021-10-29 13:21 UTC, bari12 commented on lib/rucio/db/sqla/migrate_repo/versions/9a45bc4ea66d_add_vp_table.py
> +        create_foreign_key('DID_VP_FK', 'did_virtual_placements', 'dids',
VP_DIDS_FK

2021-10-29 13:21 UTC, bari12 commented on lib/rucio/db/sqla/models.py
> +    scope = Column(InternalScopeString(get_schema_value('SCOPE_LENGTH')))
See changes in migrate script

2021-10-29 14:47 UTC, ivukotic commented
that was a massive mess up on my side. I should be more careful with the -a option. Now all of the comments should be addressed.

2021-11-16 14:09 UTC, bari12 commented
Hi Ilija,

This looks GTG, can you just rebase it please. I think that's also why the tests fail.
Also please squash the commits into one (I can do it this time, just for the next one)
Please also update https://github.com/rucio/rucio/blob/master/etc/sql/oracle/schema.sql (In a separate PR) and get this information into there too.

2021-11-16 20:30 UTC, ivukotic commented
Hi Martin,

I merged upstream changes but it still fails... now with logger thing?

Ilija

2021-11-17 15:20 UTC, bari12 commented
Ah this was an issue on master just yesterday, it is fixed, please rebase again. Sorry

2021-11-18 01:25 UTC, ivukotic commented
seems now it works. can you please merge it?

2021-11-19 11:38 UTC, bari12 approved these changes
All good, please add it in a separate PR to https://github.com/rucio/rucio/blob/master/etc/sql/oracle/schema.sql

2021-11-19 11:38 UTC, merged