Closes #5062
rucio/rucio pull request #5084
Opened 2021-12-06 19:41 UTC by Carlosbogo

Closes #5062 by replacing the link `'http://rucio.cern.ch/client_tutorial.html#adding-rules-for-replication'` with `'http://http://rucio.cern.ch/documentation/rse_expressions/'`. Also fixes a typo in the comment of line 2480.

2021-12-06 20:18 UTC, joeldierkes requested changes
Your commit message states the `how` (how did you resolve the issue), however this question can easily be answered by the commit itself (it is obvious in the commit that you interchanged the links).

Have a look at the following blog post, it describes some de facto standards on how to write commit messages: https://cbea.ms/git-commit/. While we link the corresponding issue, giving a short description in the commit itself on "why" these changes were introduced can be helpful.

Also, take a look at our documentation, we have a clear structure on how a commit message header should be formatted: https://rucio.cern.ch/documentation/contributing#contributing

2021-12-06 20:18 UTC, joeldierkes commented on bin/rucio
> +            can be found in ' + Color.BOLD + 'http://http://rucio.cern.ch/documentation/rse_expressions/' + Color.END)  # TODO:remove-deprecated
`http://` is duplicated, repeated for the other arguments as well

2021-12-07 10:38 UTC, Carlosbogo commented
Thank you very much for your help. I'm very sorry for the errors in my PR, hopefully I won't make them twice.

I read through the contributing guide and changed my  PR so that it complies with the naming and formatting conventions used in the project, but unfortunately I haven't been able to do so without creating a new PR. If there is a way to do that to keep things more organised I would love to know it.

Once again, I'm just starting contributing using Github and your tips have been very helpful. Thank you very much.

2021-12-07 12:04 UTC, joeldierkes commented
First of all, your PR looks way better than my first ones! We all started at some point.

There are some techniques which can help you:
1. If you want to change a commit, use [`git commit --amend`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---amend). This adds all the staged changes to the HEAD of the branch (the last commit).
2. If you want to push your changes, use [`git push --force <remote> <branch>`](https://git-scm.com/docs/git-push#Documentation/git-push.txt---force). This overrides the remote branch with your local one.
  It is always recommended to explicitly set the remote and branch, since there could be other changes in the repository. Also, please make sure that you __really__ don't need the changes on the remote, and that everybody else working on that branch is aware of the changes.
  The PR automatically updates after a change on the branch.

If you want to learn git for the command line, I recommend the following tutorial: https://learngitbranching.js.org/
It's also worth looking into the official git documentation: https://git-scm.com/docs

2021-12-07 12:09 UTC, Carlosbogo commented
I'll look into the resources you mention, that will help me a lot!
Thank you very much for all your help!

2021-12-08 13:03 UTC, closed without merging

2021-12-08 13:04 UTC, joeldierkes commented
Firther edited in #5084