Clients: Add `expiration-date` for upload Fix #5069
rucio/rucio pull request #5098
Opened 2021-12-08 19:08 UTC by joeldierkes

The upload command takes the `--lifetime` argument, which specifies the lifetime
of the created rule in seconds. This commit also adds the `--expiraion-date`,
which specifies the timestamp on which the rule will be obsolet. They both can't
be used the same time and `--expiration-date` has to have a fixed format to
avoid ambiguousity.

2021-12-09 11:26 UTC, mlassnig submitted a review, later dismissed

2021-12-10 15:10 UTC, bari12 requested changes

2021-12-10 15:10 UTC, bari12 commented on bin/rucio
> +    upload_parser.add_argument('--expiration-date', action='store', help='The date when the rule expires, format: <year>-<month>-<day>-<hour>:<minute>:<second>. E.g. 2022-10-20-20:00:00')
Add information that it must be UTC here.

2022-01-12 16:24 UTC, bari12 approved these changes

2022-01-12 16:24 UTC, merged