Transfers: store transfer paths in a new database table. Closes #5177
rucio/rucio pull request #5282
Opened 2022-02-23 16:28 UTC by rcarpa

Until now, a multihop transfer didn't have a real database state.
Each hop of the multihop was a separate transfer request with almost
no relationship between individual requests (only a loosely coupled
json attribute). This behavior is source of multiple issues:
 - we have recurrent problems with intermediate hops living their
own life (their lifetime should be linked to the initial request
and they shouldn't be retried on their own).
 - multiple multi-hops sharing a common sub-path are not possible
and result in permanent failures of one of the transfers until the
second finishes.
 - it doesn't allow implementation of cross-tranfertool multihops

For these particular reasons, we introduce a table storing the
relationship between independent requests of a path. I change the
workflows to rely on joins with this table:
- (1) submitter only retrieves from database requests which don't have
any pending previous hops.
- (2) submitter is capable to detect that a sub-path of the current
multi-hop transfer already exists in the database. It only creates
the link with the existing sub-path and aborts submission. Submission
automatically resumes once the common sub-path is transferred thanks to
behavior mentioned in (1)
- (3) when an intermediate hop fails, the poller/receiver will also
fail the next requests in all affected paths.

2022-02-23 16:29 UTC, rcarpa commented
This PR is based on top of #5269. Only the last commit is to be reviewed.

2022-03-08 09:43 UTC, bari12 requested changes

2022-03-08 09:43 UTC, bari12 commented on lib/rucio/db/sqla/models.py
> +class TransferHop(BASE, ModelBase):
Add this to https://github.com/rucio/rucio/blob/master/etc/sql/oracle/schema.sql as well

2022-03-08 10:09 UTC, rcarpa commented on lib/rucio/db/sqla/models.py
> +class TransferHop(BASE, ModelBase):
Done

2022-03-09 08:38 UTC, bari12 commented
Merged as feature for `1.28`

2022-03-09 08:38 UTC, bari12 approved these changes

2022-03-09 08:38 UTC, merged