Testing: Add VO Test framework
rucio/rucio pull request #5286
Opened 2022-02-24 15:51 UTC by maany

Here's what a VOTest run looks like:
https://github.com/maany/rucio/runs/5319690317?check_suite_focus=true

2022-03-07 10:24 UTC, joeldierkes requested changes

2022-03-07 10:24 UTC, joeldierkes commented on tools/test/votest_helper.py
> +    output_type.add_argument('-i', required=False,
This name is not descriptive. How about `--return-policy-package-installation-command`, or `--policy-package-installation-command`?

2022-03-07 10:24 UTC, joeldierkes commented on tools/test/votest_helper.py
> +                             help="return the rucio config section for the given vo.")
Same as above. `--get-vo-config`?

2022-03-07 10:24 UTC, joeldierkes commented on tools/test/votest_helper.py
> +                             help="return the tests that will be run for the given vo.")
`--return-test`, `--return-vo-test`?

2022-03-07 10:24 UTC, joeldierkes commented on tools/test/votest_helper.py
> +def validate(func):
A comment would be good.

2022-03-07 10:24 UTC, joeldierkes commented on etc/docker/test/matrix_policy_package_tests.yml
> +    deny:
Every time a new test file is created, it needs to be added here. This seems to add a constraint nobody will remember in the future. Can we change this to only specify the allowed ones?

2022-03-10 14:45 UTC, joeldierkes commented on etc/docker/test/matrix_policy_package_tests.yml
> +    deny:
These test files will be migrated to use the newly created factories.

2022-03-10 16:23 UTC, joeldierkes commented on tools/test/votest_helper.py
> +    parser.add_argument('-v', action='store_true',
`--verbose`

2022-03-16 09:48 UTC, bari12 approved these changes

2022-03-16 09:50 UTC, merged