Authentication & Authorisation:: Replace deprecated oauth2client dependency Closes #5343
rucio/rucio pull request #5371
Opened 2022-03-18 09:06 UTC by rizart

Replaced the oauth2client deprecated library and made the relevant changes in the GCS URL signing logic.

2022-03-31 12:43 UTC, mlassnig commented
needs rebase

2022-04-05 16:09 UTC, bari12 requested changes

2022-04-05 16:09 UTC, bari12 commented on requirements.txt
> +google-auth==2.6.0                                          # Google authentication library for Python
You need to add this too to the `server_requirements_table` in https://github.com/rucio/rucio/blob/master/setuputil.py

2022-04-05 16:25 UTC, rizart commented on requirements.txt
> +google-auth==2.6.0                                          # Google authentication library for Python
True, missed that, thanks Martin!

2022-04-06 14:35 UTC, bari12 approved these changes

2022-04-06 14:35 UTC, merged