Recovery: Implement checksum comparison to suspicious replica recoverer #5334
rucio/rucio pull request #5555
Opened 2022-05-16 13:02 UTC by ChristophAmes

Before a suspicious file which is the last remaining copy is declared bad, its checksum should be compared to varify that it is corrupt.
A new method is added to /core/replica.py which retrieves the reason for which a replica was declared bad. In a recent pull request, the given reason was changed to be the error message with which the replica failed. If the reason is related to a checksum problem, then the replica is declared bad.

2022-05-17 12:46 UTC, cserf requested changes
A few comments

2022-05-17 12:46 UTC, cserf commented on lib/rucio/core/replica.py
> +    :param name: Name of the replica DID.
Missing logger param

2022-05-17 12:46 UTC, cserf commented on lib/rucio/core/replica.py
> +                   .filter(bad_replicas_alias.rse_id.in_([rse_id]),
Why not ` filter(bad_replicas_alias.rse_id == rse_id)` ?

2022-05-17 12:46 UTC, cserf commented on lib/rucio/core/replica.py
> +                           bad_replicas_alias.scope.in_([scope]),
Same comment as before

2022-05-17 12:46 UTC, cserf commented on lib/rucio/core/replica.py
> +        result.append({'scope': scope, 'name': name, 'rse': rses[rse_id_], 'rse_id': rse_id_, 'reason': reason})
Maybe you can also keep the count ?

2022-05-17 12:46 UTC, cserf commented on lib/rucio/daemons/replicarecoverer/suspicious_replica_recoverer.py
> +                                                    auditor += 0
I guess you want to increment by 1 ?

2022-05-17 12:46 UTC, cserf commented on lib/rucio/daemons/replicarecoverer/suspicious_replica_recoverer.py
> +                                                    checksum += 0
Same comment as above

2022-05-19 16:18 UTC, cserf approved these changes
LGTM

2022-05-20 14:11 UTC, bari12 commented
I am merging this, since you avoided the new type annotation test 😄 but in principle new code (Methods) should have type annotations now.

2022-05-20 14:11 UTC, merged