Database: Add poolclass configuration option for database engine #5391
rucio/rucio pull request #5657
Opened 2022-06-21 13:11 UTC by akselaase

Adds the configuration option `poolclass` to the database section of `rucio.cfg`, which takes one of the values `queuepool` (the default) or `nullpool`. Setting the option to `nullpool` disables connection pooling in SQLAlchemy, which is useful if pooling is already performed elsewhere. Unsetting the option or setting it to `queuepool` retains the previous pooling behaviour.

2022-06-21 13:13 UTC, mlassnig commented
That was quick! :eyes:

2022-06-21 13:14 UTC, akselaase commented
It was a... good first issue.

2022-06-21 13:17 UTC, akselaase commented
Note that setting `poolclass = nullpool` conflicts with other options like `pool_size`. Should this be documented somewhere?

2022-06-21 13:17 UTC, mlassnig commented
Maybe add this to the rucio.cfg.template file?

2022-06-21 13:18 UTC, mlassnig commented
And there's of course https://github.com/rucio/documentation/ :-)

2022-06-21 14:17 UTC, akselaase commented
Added the `singletonthreadpool` choice as well, since this is the default pooling for the SQLite engine. Two more pooling mechanisms supported by SQLAlchemy could be added as well, `StaticPool` and `AssertionPool`, but I'm not sure if they are desired.

Also removed type annotations according to [Rucio Type Annotation Guide](https://codimd.web.cern.ch/6-SU3cTpQSWRK6FHkM7mAA?view).

I've submitted a PR for documentation at https://github.com/rucio/documentation/pull/139.

I'm not sure what I would add to `rucio.cfg.template`. Setting the option will incur a change of behavior, so best to just leave it like before since this is a patch PR maybe? I could add a commented line demonstrating the usage though.

2022-06-23 14:03 UTC, joeldierkes requested changes
GJ, small nits.

2022-06-23 14:03 UTC, joeldierkes commented on lib/rucio/db/sqla/session.py
> +        poolclass config option.
The second line should align with the double colons. The parameters should be documented, to be consistent with the other docs.

```python
"""Resolve the...
poolclass

:param poolclass: ...
:returns: ...
:raises ValueError: ...
"""
```

2022-06-23 14:03 UTC, joeldierkes commented on lib/rucio/db/sqla/session.py
> +        }[poolclass]
The dict is a constant, we should extract it. This also enables us to use an early return instead of the try ... catch:
```python
if poolclass not in SQLALCHEMY_POOL_TYPES:
    raise raise ValueError('Unknown poolclass: %s' % poolclass)

return SQLALCHEMY_POOL_TYPES[poolclass]
```

That's a personal choice, thoughts about that?

2022-06-23 14:03 UTC, joeldierkes commented on lib/rucio/db/sqla/session.py
> +        }[poolclass]
Also, how about calling `lower` on the poolclass variable. In case, someone uses the class name instead of the key defined by us.

2022-06-23 14:03 UTC, joeldierkes commented on lib/rucio/db/sqla/session.py
> +        raise ValueError('Unknown poolclass: %s' % poolclass)
We define our own Exception types in `lib/rucio/common/exception.py`. `InputValidationError` could work here.

2022-06-24 07:24 UTC, akselaase commented
@joeldierkes Rebased and squashed commits.

2022-06-24 09:22 UTC, joeldierkes submitted a review, later dismissed
lgtm!

2022-06-27 11:10 UTC, mlassnig approved these changes

2022-06-27 11:52 UTC, joeldierkes approved these changes

2022-07-01 11:59 UTC, bari12 commented
Although rather smaller change, I will merge this as a feature, thus it only becomes available with 1.29 (Which incidentally is now anyway)

2022-07-01 11:59 UTC, merged