Added missing web method
rucio/rucio pull request #5798
Opened 2022-08-11 13:08 UTC by ivmfnal

2022-08-12 07:46 UTC, akselaase requested changes

2022-08-12 07:46 UTC, akselaase commented on lib/rucio/web/rest/flaskapi/v1/replicas.py
> +
Should a rule also be added in the `if not with_doc:` block below? I don't know the reason for the `if`, so I can't tell myself.

2022-08-12 07:46 UTC, akselaase commented on lib/rucio/web/rest/flaskapi/v1/replicas.py
> +                                type:   string
Typo in `descritption` and some extra whitespace after `type:`

2022-08-22 07:44 UTC, bari12 approved these changes

2022-08-22 07:44 UTC, merged