Replicas: declare suspicious replicas by RSE #5906
rucio/rucio pull request #5907
Opened 2022-10-05 21:26 UTC by nsmith-

Closes #5906

2022-10-05 21:30 UTC, nsmith- commented
This will need modification once #5864 is merged

2022-11-28 09:19 UTC, cserf requested changes
Some tests directly related to this change are failing e.g. :
https://github.com/rucio/rucio/actions/runs/3192824637/jobs/5210982485
```

Declaring suspicious file replica: file://fc1c21894834461e8f50f70b9b8acdb0.cern.ch/tmp/rucio_rse/test_fc1c21894834461e8f50f70b9b8acdb0/mock/55/e5/file_CXRFCSDISP
------------------------------ Captured log call -------------------------------
DEBUG    urllib3.connectionpool:connectionpool.py:1001 Starting new HTTPS connection (1): localhost:443
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://localhost:443 "POST /replicas/suspicious HTTP/1.1" 500 76
_____________________ test_client_add_suspicious_replicas ______________________
[gw1] linux -- Python 3.8.10 /usr/bin/python
test_bad_replica.py:273: in test_client_add_suspicious_replicas
    r = replica_client.declare_suspicious_file_replicas(replicas, 'This is a good reason')
../client/replicaclient.py:99: in declare_suspicious_file_replicas
    raise exc_cls(exc_msg)
E   rucio.common.exception.RucioException: An unknown exception occurred.
E   Details: no error information passed (http status code: 500)
```
Can you please have a look and fix them ?

2022-11-28 09:19 UTC, cserf commented on lib/rucio/api/replica.py
> +    Declare a list of bad replicas.
Declare a list of suspicious replicas.

2023-04-21 15:22 UTC, nsmith- commented
This PR is a bit stale, I guess.
I think it would be a nice feature, users could for example say a replica is suspicious if a job fails to read it, and some later daemon could automate checksum verification. So I think the issue should stay open, but if the PR implementation is out of date it may be better to be closed and a new one started.

2023-04-21 15:40 UTC, bari12 commented
I agree, but it would need to be re-written then. Let's re-open when needed/somebody has time to do it.

2023-04-21 15:40 UTC, closed without merging