Conveyor: Add archive metadata to destination URLs
rucio/rucio pull request #6042
Opened 2023-01-13 11:44 UTC by mlassnig

2023-01-18 08:18 UTC, rcarpa commented on lib/rucio/core/transfer.py
> +    def __rewrite_dest_url(dest_url: str, rewrite_url: str, values: "Optional[Union[Dict, None]]" = None) -> str:
"Optional[Dict]" should be enough

2023-01-18 08:18 UTC, rcarpa commented on lib/rucio/core/transfer.py
> +            if '?' in dest_url:
Wouldn't it be easier to use the `add_url_query` function from common/utils to add the query parameters ?

2023-01-18 13:16 UTC, rcarpa requested changes
There should be changes on the protocol side to correctly handle such urls in parse_pfn

2023-01-19 16:30 UTC, bari12 commented
Closing this based on the discussion we had today in the Rucio meeting

2023-01-19 16:30 UTC, closed without merging