clients: Consistent headers + utility script #534
rucio/rucio pull request #610
Opened 2018-02-08 08:52 UTC by vingar

2018-02-08 12:14 UTC, vingar commented
problem with pylint on travis failling on
```
PYLINT FAILED
************* Module doc/source/conf.py
F:  1, 0: No module named doc/source/conf.py (fatal)
```

while it should not

2018-02-08 15:05 UTC, bari12 requested changes

2018-02-08 15:05 UTC, bari12 commented on tools/pip-requires
> +kerberos>=1.2.5             # Kerberos high-level interface
Something is wrong with this PR. It adds the dependencies we excluded again.

2018-02-09 08:17 UTC, vingar commented
ah, I wrongly rebased against next to solve a conflict (but this impacted the one on master). I'll split ti up  in several PRs.

2018-02-09 11:34 UTC, bari12 commented
Ok, I'll close this then.

2018-02-09 11:34 UTC, closed without merging