Authentication & Authorisation: Add get_auth_token_ssh check code. Fix #6119
rucio/rucio pull request #6136
Opened 2023-03-16 17:36 UTC by bjwhite-fnal

2023-03-17 12:14 UTC, dchristidis reviewed
Though I have no reservation against this proposed fix, I can’t help but wonder: why do we need two permissions for the same flow? Is there any scenario where the Rucio administrators might want to allow one but deny the other?

Looking at commit 6871028 where this issue was introduced, there is no argument against the proposed fix being what the author omitted, but what I’m questioning is the original design.

2023-04-19 15:17 UTC, bari12 commented
I kind of agree, I would just use `perm_get_auth_token_ssh` for both the challenge and auth token.

2023-04-26 07:03 UTC, dchristidis requested changes, later dismissed
Well done. I hope you won’t mind my being pedantic, but please prefix the commit message with a component (the shortened ‘Authentication:’ or ‘Auth:’ should be enough). The I guess the already included colon would be better replaced with a semicolon.

2023-04-26 07:03 UTC, dchristidis commented on lib/rucio/core/permission/generic.py
> +    Checks if an account can request an ssh token.
Please capitalise ‘SSH’.

2023-05-01 15:28 UTC, bjwhite-fnal commented
I don't think I asked for this, but when this does eventually get merged could we please have it backported to 1.29? Thanks!

2023-05-05 13:43 UTC, bari12 approved these changes

2023-05-05 13:43 UTC, merged

2023-05-05 13:48 UTC, bari12 commented
@bjwhite-fnal This is merged, but the cherry-picking to the 1.29 release branch is a bit cumbersome. Can you submit a second PR specifically for the release-1.29-LTS branch with these changes. You can skip all the type checking changes, since they are not necessary for 1.29. Thanks!