Remove temporary DIDs functionality #6317
rucio/rucio pull request #6346
Opened 2023-10-05 15:21 UTC by dchristidis

This feature is not used by any community, nor is it maintained. It was agreed to remove it entirely. This is done in a single commit which affects multiple components:

Deletion: Remove Light Reaper
Clients: Remove add_temporary_dids()
REST & API: Remove 'tmp_dids' endpoint
Core & Internals: Remove files related to temporary DIDs
Testing: Remove files related to temporary DIDs and Light Reaper
Database: Remove model; add migration script

2023-10-06 13:19 UTC, dchristidis commented
The failing test is due to the content of the `rucio.cfg` file in the latest `rucio-dev` container. It’s addressed in rucio/containers#261.

2023-11-01 13:48 UTC, bari12 requested changes
LGTM
One minor change:
Please also adapt https://github.com/rucio/rucio/blob/master/etc/sql/oracle/schema.sql

2023-11-01 17:13 UTC, dchristidis commented
Well spotted, thank you. The file has comments with numbered comments. I decided it’s not worth renumbering them for such a change, thus leaving behind a gap.

2023-11-02 12:48 UTC, bari12 approved these changes

2023-11-02 12:49 UTC, merged