REST & API: uniform case for urls in flask subscription endpoint Fix: #6316
rucio/rucio pull request #6393
Opened 2023-11-28 20:11 UTC by voetberg

Addressing #6316 

As stated in the comment there - this is almost certainly a minor mistake. Alt solution would be setting up a automatic redirect for variants of urls with mixed case - which would be a larger undertaking and a separate issue.

2024-01-23 14:47 UTC, bari12 requested changes
I think this will break backwards compatibility. Because you might still have old clients (pre your change) going against the upper-case endpoints. And in this case, the server will reply a 404. 

We probably have to add rules for both, the lower-case endpoint and the previous uppercase endpoint and take it out once the `33` clients fall out of the legacy window. (Which will be the Rucio `38` release)

2024-02-14 16:23 UTC, bari12 commented on lib/rucio/web/rest/flaskapi/v1/subscriptions.py
> +    # Legacy url support
Please add a comment:
`TODO: Take out with Rucio 38` :-)

2024-02-21 12:41 UTC, bari12 requested changes
One last change 😄

2024-02-21 12:41 UTC, bari12 commented on lib/rucio/web/rest/flaskapi/v1/subscriptions.py
> +    bp.add_url_rule('/<account>/<name>/Rules', view_func=rules_view, methods=['get', ])
I think one legacy rule is missing
`/<account>/Rules/States`

2024-03-07 16:16 UTC, voetberg commented
Test failure due to infamous download_pfns - otherwise everything in the clear :o

2024-04-09 11:24 UTC, bari12 commented
Please rebase and let's run the tests again.

2024-05-28 12:54 UTC, bari12 approved these changes

2024-05-28 12:54 UTC, merged