dirac: add metadata method in add_files for dirac #6437
rucio/rucio pull request #6438
Opened 2024-01-05 18:55 UTC by panta-123

Marked as draft PR as it is not tested yet.

I wanted to get some comments/green light on the idea before testing. 
Especially from those using rucio and dirac.

@cserf , Is this acceptable from Belle II point of view ?

2024-01-05 19:53 UTC, panta-123 commented
The add_files method with metadata , test passed.

`[gw1] [ 57%] PASSED tests/test_belleii.py::test_dirac_addfile_with_parents_meta `.
Will clean up the type annotation and code format latter.

2024-01-08 08:06 UTC, cserf commented
A few tests are failing (syntax checks and docs), but except that, looks good to to me. Can be merged when the test are fixed

2024-01-08 17:07 UTC, panta-123 commented
All the check passed. 
The failed End to END integration test is not related to this PR.

2024-01-11 14:41 UTC, cserf approved these changes, later dismissed

2024-01-17 14:00 UTC, bari12 requested changes

2024-01-17 14:00 UTC, bari12 commented on lib/rucio/api/dirac.py
> -def add_files(lfns, issuer, ignore_availability, vo='def', *, session: "Session"):
Add `parents_metadata` to the method description (param) below

2024-01-17 14:00 UTC, bari12 commented on lib/rucio/client/diracclient.py
> -    def add_files(self, lfns, ignore_availability=False):
Add parameter to description

2024-01-17 14:37 UTC, panta-123 commented on lib/rucio/api/dirac.py
> -def add_files(lfns, issuer, ignore_availability, vo='def', *, session: "Session"):
done

2024-01-17 14:37 UTC, panta-123 commented on lib/rucio/client/diracclient.py
> -    def add_files(self, lfns, ignore_availability=False):
done

2024-01-22 11:30 UTC, bari12 approved these changes
I am merging this as an enhancement within the `33` release line.

2024-01-22 11:30 UTC, bari12 commented
Also please squash commits next time :-)

2024-01-22 11:30 UTC, merged