Transfers: metrics API endpoint, allow to group RSEs by attribute in response
rucio/rucio pull request #6567
Opened 2024-03-14 15:38 UTC by rdimaio

Usage: `requests/metrics?group_response_by=[attr]`

Note: I didn't test this as I am not yet sure how to test API requests. I would appreciate some guidance on this if possible.

Fix #6564

2024-03-19 08:05 UTC, dchristidis requested changes
I’m concerned that the name `group_response_by` and the documentation around it can be misleading or not intuitive. I would be more precise that this is about RSE attributes.

Also, links should not be silently omitted if the RSE attribute does not exist (maybe use something like `rse.attributes.get(key, 'UNKNOWN')` instead ?)

2024-03-19 08:11 UTC, rdimaio commented
> I’m concerned that the name `group_response_by` and the documentation around it can be misleading or not intuitive. I would be more precise that this is about RSE attributes.
> 
> Also, links should not be silently omitted if the RSE attribute does not exist (maybe use something like `rse.attributes.get(key, 'UNKNOWN')` instead ?)

@dchristidis thanks for the comments. Would `group_response_by_rse_attribute` be an acceptable name or do you have other suggestions?

2024-03-20 09:18 UTC, dchristidis commented
The presence of ‘response’ feels unnecessary. Maybe `group_by_attribute` or `group_by_rse_attribute`?

2024-03-20 11:37 UTC, rdimaio commented
Please ignore the changes in `test_request.py` that I accidentally added in the first force-push; I reverted them in the second force-push

2024-06-04 12:39 UTC, rdimaio commented
Rebased in latest force-push

2024-06-04 15:14 UTC, bari12 approved these changes

2024-06-04 15:14 UTC, merged