Clients: don't return success from uploader when registration fails #6670
rucio/rucio pull request #6754
Opened 2024-05-03 14:03 UTC by jamesp-epcc

This PR ensures that the upload client will not return success if updating the replica state or attaching to a dataset fails. Previously if the Rucio server timed out during one of these operations the upload was still flagged as a success and there was no way for the caller to detect the registration failure.

2024-05-10 11:10 UTC, rdimaio approved these changes, later dismissed
We should add a unit test at some point to assert `num_succeeded` is as expected

2024-05-10 14:57 UTC, bari12 requested changes
LGTM, but as @rdimaio already mentioned, please add a unit test for this right away, so we make sure this does not regress in the future

2024-05-13 13:29 UTC, jamesp-epcc commented
I've added a unit test that simulates the replica state update timing out and ensures that an exception is thrown as a result.

2024-05-14 07:19 UTC, rdimaio approved these changes

2024-05-22 15:12 UTC, bari12 approved these changes

2024-05-22 15:12 UTC, merged