Auth: Refactor BaseClient._get_creds to read from config even if creds are set
rucio/rucio pull request #6856
Opened 2024-06-27 14:08 UTC by rdimaio

Fix #6846

2024-07-02 12:49 UTC, maxnoe commented
Can we refactor this a bit further so that

* All options have a clear precedence of (from lowest to highest priority):
    * default value
    * configuration file
    * environment variable
    * `creds` argument

* take care that when checking the configuration file, no `No such section` error is thrown?
   I think for this, it might be easiest if the `config_get(section, name, default)` function would just return `default` in case the section doesn't exist instead of raising an error.


When using the cli or inside a docker container, it would be nice if rucio wouldn't need a configuration file at all when everything is defined either as arguments or via env variables. 


As far as I can tell there are a couple of options for which there are neither env variables nor cli options, just the configuration file value.

2024-07-02 12:53 UTC, rdimaio commented
> Can we refactor this a bit further so that
> 
>     * All options have a clear precedence of (from lowest to highest priority):
>       
>       * default value
>       * configuration file
>       * environment variable
>       * `creds` argument
> 
>     * take care that when checking the configuration file, no `No such section` error is thrown?
>       I think for this, it might be easiest if the `config_get(section, name, default)` function would just return `default` in case the section doesn't exist instead of raising an error.
> 
> 
> When using the cli or inside a docker container, it would be nice if rucio wouldn't need a configuration file at all when everything is defined either as arguments or via env variables.
> 
> As far as I can tell there are a couple of options for which there are neither env variables nor cli options, just the configuration file value.

I agree, but I think it might be best to do this in a follow-up PR so that we can merge your changes from https://github.com/rucio/rucio/pull/6848 first

2024-07-02 12:56 UTC, maxnoe commented
@rdimaio I wasn't yet totally sure how to implement #6848 properly, i.e. the error handling in case something is empty or not valid. So it has a large overlap.

I thought maybe doing this on one go, as one has to basically touch all lines here in this _get_creds function might be easiest.

2024-07-02 13:19 UTC, voetberg commented on lib/rucio/client/baseclient.py
> +                if 'oidc_refresh_lifetime' not in creds or creds['oidc_refresh_lifetime'] is None:
All of these if "key" not in creds or creds['key'] is None could be replaced with 

```
if creds.get('key') is None: 
```

For legibility

2024-07-02 13:22 UTC, voetberg commented on lib/rucio/client/baseclient.py
> +                if 'oidc_refresh_lifetime' not in creds or creds['oidc_refresh_lifetime'] is None:
This who oidc auth block could also probably be a for loop, just looping through a list of the keys - A debug log would be able to track where errors happened in this case. The whole block is just a lot to read.

2024-07-02 13:36 UTC, voetberg requested changes
I largely agree with @maxnoe 's comments here - There should be a clear logic for order of preference on the auth variables (I was having a hard time with #6839 for this exact reason). 

Maybe a better solution would be to have a smaller helper function that went through and checked each place a single auth variable can be found in order to keep _get_creds form exploding into hydra of a function

2024-07-08 07:46 UTC, bari12 commented
Should we split this up into two different issues? I would like to fix the regression in the upcoming release.

2024-07-08 09:19 UTC, rdimaio commented
> Should we split this up into two different issues? I would like to fix the regression in the upcoming release.

I think it would be best to merge @maxnoe's PR first: https://github.com/rucio/rucio/pull/6848 - I can then adapt my PR to that one and address @voetberg 's comments

2024-07-17 11:56 UTC, bari12 commented
I am merging this now, because the fix should be included in the 35.0.0 release. But please let's continue to include the other points mentioned in @maxnoe PR #6848 for the following release.

2024-07-17 11:56 UTC, bari12 approved these changes

2024-07-17 11:56 UTC, merged