Patch branch
rucio/rucio pull request #892
Opened 2018-03-13 12:06 UTC by tushar-97

Documentation: Fixing grammatical errors in the documentation #886

2018-03-13 14:17 UTC, bari12 commented
Hi @tushar-97 ,
The second PR according to the https://github.com/rucio/rucio/blob/master/CONTRIBUTING.rst guide is missing. Please add.

2018-03-13 14:55 UTC, tushar-97 commented
Hi @bari12 
I have added the second PR for the next branch. #905

2018-03-14 10:25 UTC, bari12 requested changes

2018-03-14 10:25 UTC, bari12 commented on doc/source/replica_workflow.rst
> +The hash deterministic algorithm is an algorithm commonly used in Rucio. The advantage of this algorithm is that, due to the characteristics of cryptographic hash functions,the files are evenly distr
Space missing after comma

2018-03-14 11:44 UTC, tushar-97 commented
@bari12 Please review. I have made the necessary changes in both the PRs.

2018-03-14 11:46 UTC, bari12 commented
Hi @tushar-97 
It's fine now but I just realised you a separate branch for the second PR. This is really not needed. You can do the two PRs (one against master, one against next) from the same branch. `tushar-97:patch-branch`. So repeating the work on the next branch was really not needed 😄

2018-03-14 11:51 UTC, vingar approved these changes

2018-03-14 12:03 UTC, tushar-97 commented
Hi @bari12 
Thanks for your patience and helping me out with this PR. I have submitted another PR #911 (for next) with the correct branch. I hope this is sufficient.

2018-03-14 13:36 UTC, bari12 approved these changes

2018-03-14 13:36 UTC, merged